---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slack-bot-binding
  namespace: slack-bot
subjects:
- kind: ServiceAccount
  name: slack-bot-sa
  namespace: slack-bot
roleRef:
  kind: Role
  name: slack-bot-role
  apiGroup: rbac.authorization.k8s.io
