---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: slack-bot-role
  namespace: slack-bot
rules:
# Minimal permissions - no cluster-wide access
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["slack-secrets"]
