---
apiVersion: v1
kind: Secret
metadata:
  name: slack-secrets
  namespace: slack-bot
type: Opaque
stringData:
  # Slack Bot Token - replace with actual values
  SLACK_BOT_TOKEN: "xoxb-your-bot-token-here"
  # Slack Signing Secret for webhook verification
  SLACK_SIGNING_SECRET: "your-signing-secret-here"
  # Slack App Token for Socket Mode (if needed)
  SLACK_APP_TOKEN: "xapp-your-app-token-here"
  # Slack Team ID
  SLACK_TEAM_ID: "T1234567890"
  # Slack Channel IDs (comma-separated)
  SLACK_CHANNEL_IDS: "C1234567890,C0987654321"
